// "Draft from repository": the one-button AI flow. Given a repo (and optional
// PR), it drafts the description and why, reconstructs the app's UI pages as
// mockup images from the HTML/CSS/JS evidence, assembles a how-it-works PDF,
// and hands everything to a DraftTarget (the Add-project form stashes; the
// project pages commit). The images are AI reconstructions of the interface,
// not screenshots of the running app.

import { z } from 'astro/zod';
import { completeStructured } from './provider';
import { collectUiEvidence, serializeContext, type EvidenceSource } from './evidence';
import { aiComplete, collectProjectEvidence } from '../ai-complete';

export interface DraftTarget {
  projectName: string;
  existingDescription: string;
  existingWhy: string;
  /** filenames already attached — signal for the drafts, and collision avoidance */
  existingArtifacts: string[];
  status: (message: string) => void;
  applyText: (fields: { description: string; why: string }) => Promise<void>;
  addArtifact: (filename: string, base64: string) => Promise<void>;
}

export interface DraftResult {
  description: string;
  why: string;
  artifactNames: string[];
}

const uiPageSchema = z.object({
  name: z.string(),
  purpose: z.string(),
  controls: z.array(z.string()).default([]),
  html: z.string(),
});

const uiStudySchema = z.object({
  appName: z.string(),
  overview: z.string(),
  pages: z.array(uiPageSchema).min(1).max(6),
});
type UiStudy = z.infer<typeof uiStudySchema>;

const UI_SYSTEM = `You are a UI reconstructor. From a web project's HTML/CSS/JS/component source files, reconstruct what the application's screens look like and how they behave.

For each distinct page or screen (up to 6, most important first) produce:
- "name" and one-sentence "purpose"
- "controls": what each interactive control does, deduced from the scripts/handlers (e.g. "Status dropdown — filters the list client-side")
- "html": a single self-contained mockup of the page. Rules for the html:
  * one <style> block with all CSS inlined — copy the real colors, fonts, spacing, and layout from the CSS evidence as faithfully as possible
  * absolutely no external resources: no <script>, no <img src=http…>, no @import, no url(...) — represent images as styled placeholder divs labeled with text
  * design for a 1280×800 viewport; fill it with representative example content so the page looks alive

Also write "overview": two or three plain-English paragraphs explaining what the app is and how someone uses it.`;

// --- rasterize a self-contained HTML mockup to PNG via SVG foreignObject ---
async function htmlToPngBase64(html: string, width = 1280, height = 800): Promise<string> {
  // foreignObject needs well-formed XHTML — round-trip through the DOM parser
  const parsed = new DOMParser().parseFromString(html, 'text/html');
  parsed.querySelectorAll('script, iframe, object, embed, link').forEach((node) => node.remove());
  const xhtml = new XMLSerializer().serializeToString(parsed.documentElement);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><foreignObject width="100%" height="100%">${xhtml}</foreignObject></svg>`;
  // data: URL, not a blob URL — Chromium taints the canvas for blob-loaded
  // foreignObject SVGs, and a tainted canvas cannot be exported to PNG
  const url = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
  const image = await new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error('The mockup could not be rendered.'));
    img.src = url;
  });
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const context = canvas.getContext('2d')!;
  context.fillStyle = '#ffffff';
  context.fillRect(0, 0, width, height);
  context.drawImage(image, 0, 0);
  const dataUrl = canvas.toDataURL('image/png');
  return dataUrl.slice(dataUrl.indexOf(',') + 1);
}

// --- assemble the how-it-works PDF (title + overview, then one page per screen) ---
async function buildPdfBase64(study: UiStudy, images: { name: string; purpose: string; controls: string[]; base64: string }[]): Promise<string> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const textWidth = pageWidth - margin * 2;

  doc.setFont('helvetica', 'bold').setFontSize(24).text(`How ${study.appName} works`, margin, 72);
  doc.setFont('helvetica', 'normal').setFontSize(11);
  doc.text(doc.splitTextToSize(study.overview, textWidth), margin, 108);
  doc.setFontSize(8).setTextColor(120).text('Generated by AI from the repository source — UI images are reconstructions, not screenshots.', margin, doc.internal.pageSize.getHeight() - 24);

  for (const image of images) {
    doc.addPage();
    doc.setTextColor(0).setFont('helvetica', 'bold').setFontSize(16).text(image.name, margin, 48);
    doc.setFont('helvetica', 'normal').setFontSize(10).text(doc.splitTextToSize(image.purpose, textWidth), margin, 66);
    const imgWidth = textWidth;
    const imgHeight = imgWidth * (800 / 1280);
    doc.addImage(`data:image/png;base64,${image.base64}`, 'PNG', margin, 84, imgWidth, imgHeight);
    if (image.controls.length) {
      let y = 84 + imgHeight + 20;
      doc.setFont('helvetica', 'bold').setFontSize(10).text('Controls', margin, y);
      doc.setFont('helvetica', 'normal').setFontSize(9);
      for (const control of image.controls.slice(0, 8)) {
        y += 14;
        doc.text(doc.splitTextToSize(`• ${control}`, textWidth), margin, y);
      }
    }
  }
  return (doc.output('datauristring') as string).split(',')[1];
}

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'page';

const uniqueName = (base: string, taken: Set<string>) => {
  let name = base;
  let counter = 2;
  const dot = base.lastIndexOf('.');
  while (taken.has(name)) name = `${base.slice(0, dot)}-${counter++}${base.slice(dot)}`;
  taken.add(name);
  return name;
};

export async function draftFromRepository(
  token: string,
  repositoryUrl: string,
  pullRequestUrl: string,
  target: DraftTarget,
): Promise<DraftResult> {
  target.status('Reading the repository…');
  const context = await collectProjectEvidence(token, repositoryUrl, pullRequestUrl);
  const contextText = serializeContext(context);

  target.status('Drafting the description…');
  const description = await aiComplete({ field: 'description', existing: target.existingDescription, projectName: target.projectName, context: contextText });
  target.status('Drafting why it was built…');
  const existingWhy = target.existingArtifacts.length
    ? `${target.existingWhy}\n\n(Artifacts already attached: ${target.existingArtifacts.join(', ')})`
    : target.existingWhy;
  const why = await aiComplete({ field: 'why', existing: existingWhy, projectName: target.projectName, context: contextText });
  await target.applyText({ description, why });

  const artifactNames: string[] = [];
  target.status('Studying the UI source files…');
  const uiSources: EvidenceSource[] = await collectUiEvidence(token, repositoryUrl);
  if (uiSources.length) {
    target.status('Reconstructing the UI pages…');
    const study = await completeStructured({
      system: UI_SYSTEM,
      user: `Project: ${target.projectName}\n\nSource files:\n${uiSources.map((s) => `## ${s.ref}\n${s.text}`).join('\n\n')}\n\nReturn JSON: {"appName": string, "overview": string, "pages": [{"name": string, "purpose": string, "controls": [string], "html": string}]}`,
      schema: uiStudySchema,
      maxTokens: 8000,
    });

    const taken = new Set(target.existingArtifacts);
    const images: { name: string; purpose: string; controls: string[]; base64: string }[] = [];
    for (const page of study.pages) {
      try {
        images.push({ name: page.name, purpose: page.purpose, controls: page.controls, base64: await htmlToPngBase64(page.html) });
      } catch {
        // a bad mockup shouldn't sink the run
      }
    }
    for (const image of images) {
      const filename = uniqueName(`ui-${slugify(image.name)}.png`, taken);
      target.status(`Attaching ${filename}…`);
      await target.addArtifact(filename, image.base64);
      artifactNames.push(filename);
    }
    if (images.length) {
      target.status('Building the how-it-works PDF…');
      const pdfName = uniqueName(`how-${slugify(study.appName)}-works.pdf`, taken);
      await target.addArtifact(pdfName, await buildPdfBase64(study, images));
      artifactNames.push(pdfName);
    }
  }

  return { description, why, artifactNames };
}
